# Use the official Python 3.11.9 image as the base image
FROM python:3.11.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Run Test1.py when the container launches
CMD ["python", "Test1.py"]
